# Generated by Django 5.0 on 2023-05-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=50, verbose_name="Phone")),
                ("address", models.CharField(max_length=50, verbose_name="Address")),
                ("instagram", models.URLField(verbose_name="Instagram URL")),
                ("facebook", models.URLField(verbose_name="Facebook URL")),
            ],
            options={
                "verbose_name": "Contact Details",
                "verbose_name_plural": "Contact Details",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=50, verbose_name="Phone")),
                ("subject", models.CharField(max_length=50, verbose_name="Subject")),
                ("message", models.TextField(max_length=500, verbose_name="Message")),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Date")),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
    ]
