services:
  db:
    <<: &db
      image: postgres:14.2-alpine
      container_name: codeshift_db
      restart: unless-stopped
      volumes:
        - pgdata:/var/lib/postgresql/data/
      env_file:
        - ./config/.env
      networks:
        - webdata

volumes:
  pgdata:
    driver: local
    name: codeshift_pgdata

networks:
  webdata:
    driver: bridge
    name: codeshift_webdata
