version: "3"

services:
  web:
    image: "codeshift:dev"
    build:
      target: development_build
      context: .
      dockerfile: ./docker/django/Dockerfile
    restart: always
    command: python -Wd manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - static:/var/www/static
      - media:/var/www/media
    environment:
      - DJANGO_ENV=development
    ports:
      - 8000:8000

volumes:
  static:
  media: