version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    restart: always
    command: python -Wd manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000