# Generated by Django 4.2 on 2023-05-16 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('name_az', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('name_az', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('title_az', models.CharField(max_length=250, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=250, null=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_az', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('client', models.CharField(max_length=50, verbose_name='Client')),
                ('client_az', models.CharField(max_length=50, null=True, verbose_name='Client')),
                ('client_en', models.CharField(max_length=50, null=True, verbose_name='Client')),
                ('client_ru', models.CharField(max_length=50, null=True, verbose_name='Client')),
                ('website', models.CharField(blank=True, max_length=250, null=True, verbose_name='Website')),
                ('banner', models.ImageField(upload_to='portfolio/banners', verbose_name='Banner')),
                ('cover', models.ImageField(upload_to='portfolio/covers', verbose_name='Cover')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=250, verbose_name='Point')),
                ('point_az', models.CharField(max_length=250, null=True, verbose_name='Point')),
                ('point_en', models.CharField(max_length=250, null=True, verbose_name='Point')),
                ('point_ru', models.CharField(max_length=250, null=True, verbose_name='Point')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='portfolio.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'ProjectPoint',
                'verbose_name_plural': 'ProjectPoints',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/images', verbose_name='Image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'ProjectImage',
                'verbose_name_plural': 'ProjectImages',
            },
        ),
    ]
