version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d/:ro
      - static:/var/www/static:ro
      - media:/var/www/media:ro
    networks:
      - webnet
    depends_on:
      - web
  
  web:
    <<: &web
      image: codeshift:prod
      build:
        target: production_build
      command: bash ./docker/django/gunicorn/start.sh
      environment:
        - DJANGO_ENV=production
      env_file:
        - ./config/.env
      networks:
        - webnet


volumes:
  static:
  media:


networks:
  webnet:
    driver: bridge