version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d/:ro
      - ./docker/certbot/www/:/var/www/certbot/:ro
      - ./docker/certbot/conf/:/etc/nginx/ssl/:ro
      - static:/var/www/static:ro
      - media:/var/www/media:ro
    networks:
      - webnet
      - webcert
    depends_on:
      - web
      - certbot

  certbot:
    image: certbot/certbot:latest
    # command: certonly --webroot -w /var/www/certbot --force-renewal --email ${TLS_EMAIL} -d ${DOMAIN_NAME} --agree-tos
    # command: certonly --test-cert --webroot -w /var/www/certbot --email ${TLS_EMAIL} -d ${DOMAIN_NAME} --agree-tos
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    env_file:
      - ./config/.env
    volumes:
      - ./docker/certbot/www/:/var/www/certbot/:rw
      - ./docker/certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - webcert
  
  web:
    <<: &web
      image: codeshift:prod
      build:
        target: production_build
      command: bash ./docker/django/gunicorn/start.sh
      environment:
        - DJANGO_ENV=production
      env_file:
        - ./config/.env
      networks:
        - webnet


volumes:
  static:
  media:


networks:
  webnet:
    driver: bridge
  webcert:
    driver: bridge